portfolio/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/doc/", include("django.contrib.admindocs.urls")),
    path("admin/", admin.site.urls),
    path("", include("projects.urls")),
]

projects/urls.py
from django.urls import path

from projects.views import HomePageView, ProjectDetailView


app_name = "projects"
urlpatterns = [
    path("project/<int:pk>", ProjectDetailView.as_view(), name="project-details"),
    path("", HomePageView.as_view(), name="homepage"),
]

common/models.py
from django.db import models

# Create your models here.

projects/models.py
from django.db import models


class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    technology = models.CharField(max_length=20)
    image = models.CharField(max_length=100)

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    pass

common/views.py
from django.shortcuts import render

# Create your views here.

projects/views.py
from django.views.generic import DetailView, TemplateView
from projects.models import Project
from django.urls import reverse


class HomePageView(TemplateView):
    template_name = "projects/all_projects.html"

    def get_context_data(self, **kwargs):
        # Query the db to return all project objecst
        context = super().get_context_data(**kwargs)
        context["projects"] = Project.objects.all()
        return context


class ProjectDetailView(DetailView):
    model = Project
    template_name = "projects/project_detail.html"

    def get_absolute_url(self):
        return reverse("project-details")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["pk"] = self.object.pk
        return context

templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <!-- <link rel="stylesheet" href="{% static 'css/main.css' %}"> -->
        <title>{% block title %}{% endblock %} | Portfolio</title>
    {% endblock %}
</head>
<body>
    {% block body %}

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand" href="{% url 'projects:homepage' %}">Portfolio</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
        
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                    <a class="nav-link" href="{% url 'projects:homepage' %}">Home</a>
                    </li>
                    <li class="nav-item">
                    <a class="nav-link" href="/admin/">admin</a>
                    </li>
                </ul>
                </div>
            </div>
        </nav>

        <div class="container">

            {% block main %}{% endblock %}

        </div>

        
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
        <!-- <script src="{% static 'js/main_js.js' %}"></script> -->
    {% endblock %}
</body>
</html>

templates/projects/all_projects.html
{% extends '_base.html' %}
{% load static %}

{% block title %}Home{% endblock %}
{% block main %}
            <h1>Projects</h1>
        <div class="row">
            {% for project in projects %}
                <div class="col-md-4">
                    <div class="card mb-2">
                        <img class="card-img-top" src="{% static project.image %}" alt="{{ project.description }}">
                        <div class="card-body">
                            <h5 class="card-title">{{ project.title }}</h5>
                            <p class="card-text">{{ project.description }}</p>
                            <a href="{% url 'projects:project-details' project.pk %}" class="btn btn-primary">Read More</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
{% endblock %}

templates/projects/project_detail.html
{% extends '_base.html' %}
{% load static %}

{% block title%}Details{% endblock %}
{% block main %}
    <h1>{{ project.title }}</h1>
    <div class="row">
        <div class="col-md-8">
            <img src="{% static project.image %}" alt="{{ project.description }}" width="100%">
        </div>
        <div class="col-md-4">
            <h5>About the project</h5>
            <p>{{ project.description }}</p>
            <h5>Built with:</h5>
            <p>{{ project.technology }}</p>
        </div>
    </div>
{% endblock %}